apiVersion: v1
kind: Pod
metadata:
  name: admin-webapp
  labels:
    app: admin-webapp
spec:
  containers:
  - name: admin-webapp
    image: admin-webapp
    imagePullPolicy: Never
    env:
    - name: SWTM_STAGE
      value: prod
    ports:
    - containerPort: 8080