apiVersion: v1
kind: Pod
metadata:
  name: resources
  labels:
    app: resources
spec:
  containers:
  - name: resources
    image: resources
    imagePullPolicy: Never
    env:
    - name: SWTM_STAGE
      value: prod
    ports:
    - containerPort: 8080