apiVersion: v1
kind: Pod
metadata:
  name: mainspring
  labels:
    app: mainspring
spec:
  containers:
  - name: mainspring
    image: mainspring
    imagePullPolicy: Never
    env:
    - name: JAVA_OPTS
      value: -Djboss.http.port=8081 -DCASSANDRA_URI=cassandra-service:9160 -DCASSANDRA_CQL_URI=cassandra-service
    ports:
    - containerPort: 8081