apiVersion: v1
kind: Service
metadata:
  name: cassandra-service
spec:
  selector:
    app: cassandra
  ports:
  - name: cassandra-tcp
    protocol: TCP
    port: 9160
    nodePort: 0
  - name: cassandra-cql
    protocol: TCP
    port: 9042
    nodePort: 0