apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: activemq
  ports:
  - name: activemq1
    protocol: TCP
    port: 8161
    nodePort: 0
  - name: activemq2
    protocol: TCP
    port: 61616
    nodePort: 0
  - name: activemq3
    protocol: TCP
    port: 5672
    nodePort: 0
  - name: activemq4
    protocol: TCP
    port: 61613
    nodePort: 0
  - name: activemq5
    protocol: TCP
    port: 1883
    nodePort: 0
  - name: activemq6
    protocol: TCP
    port: 61614
    nodePort: 0