apiVersion: v1
kind: Pod
metadata:
  name: analytics
  labels:
    app: analytics
spec:
  containers:
  - name: analytics
    image: analytics
    imagePullPolicy: Never
    env:
    - name: JAVA_OPTS
      value: -DschemaGen=create-drop -Dorg.apache.activemq.SERIALIZABLE_PACKAGES="java.util,java.lang,java.math,java.time,at.ac.tuwien.swtm"
    - name: SWTM_STAGE
      value: prod
    ports:
    - containerPort: 8080